#!/bin/bash
# Quick Start Script for Testing GAIC Detector with Grad-CAM
# This script helps you test the frontend can display Grad-CAM heatmaps

set -e

echo "========================================"
echo "GAIC Detector - Grad-CAM Test Guide"
echo "========================================"
echo ""
echo "This guide helps you verify the Grad-CAM implementation works end-to-end."
echo ""
echo "Prerequisites:"
echo "✓ conda environment 'gaic-detector' activated"
echo "✓ AIDE model weights in models/weights/GenImage_train.pth"
echo "✓ All dependencies installed (grad-cam, open-clip-torch, etc.)"
echo ""
echo "========================================"
echo "Step 1: Verify Structure"
echo "========================================"
echo ""
echo "Running structure verification test..."
conda run -n gaic-detector python test_gradcam_simple.py

if [ $? -ne 0 ]; then
    echo ""
    echo "❌ Structure test failed. Please fix the issues above."
    exit 1
fi

echo ""
echo "========================================"
echo "Step 2: Start Backend Server"
echo "========================================"
echo ""
echo "To start the backend, run in a separate terminal:"
echo ""
echo "    conda activate gaic-detector"
echo "    python -m app.main"
echo ""
echo "The backend will start on http://localhost:8000"
echo ""
echo "========================================"
echo "Step 3: Start Frontend (Gradio)"
echo "========================================"
echo ""
echo "To start the frontend, run in another terminal:"
echo ""
echo "    conda activate gaic-detector"
echo "    python gradio_app.py"
echo ""
echo "The frontend will start on http://localhost:7860"
echo ""
echo "========================================"
echo "Step 4: Test Grad-CAM"
echo "========================================"
echo ""
echo "1. Open http://localhost:7860 in your browser"
echo "2. Go to the 'Image Analysis' tab"
echo "3. Make sure 'Include Grad-CAM Heatmap' is checked (default)"
echo "4. Upload a test image (any JPG/PNG)"
echo "5. Click 'Analyze Image'"
echo ""
echo "Expected Results:"
echo "✅ Score displayed (0-100)"
echo "✅ Original image shown on the left"
echo "✅ Grad-CAM heatmap overlay shown on the right"
echo "✅ Colored heatmap (blue-green-yellow viridis colormap)"
echo ""
echo "If heatmap is missing:"
echo "❌ Check backend logs for 'Grad-CAM' errors"
echo "❌ Check browser console for API errors"
echo "❌ Verify heatmap_png_b64 is not null in API response"
echo ""
echo "========================================"
echo "Step 5: Test API Directly (Optional)"
echo "========================================"
echo ""
echo "Test the API with curl:"
echo ""
echo "    curl -X POST http://localhost:8000/analyze/image \\"
echo "      -F 'file=@test_image.jpg' \\"
echo "      -F 'include_heatmap=true' \\"
echo "      | jq '.heatmap_png_b64' | head -c 50"
echo ""
echo "Expected: Base64 string starting with 'iVBORw0KGgo...'"
echo ""
echo "========================================"
echo "Troubleshooting"
echo "========================================"
echo ""
echo "Issue: 'Module not found: grad_cam'"
echo "Fix: conda activate gaic-detector && pip install grad-cam"
echo ""
echo "Issue: 'Model weights not found'"
echo "Fix: Download GenImage_train.pth to models/weights/"
echo ""
echo "Issue: 'CUDA out of memory'"
echo "Fix: Model will auto-fallback to CPU (slower but works)"
echo ""
echo "Issue: 'Heatmap is null'"
echo "Check: Backend logs for Grad-CAM errors"
echo "Check: errors[] field in API response"
echo ""
echo "========================================"
echo "✅ Setup guide complete!"
echo "========================================"
echo ""
echo "Next: Follow Steps 2-4 above to test the system."
echo ""
