"""Report generation with Gemini LLM and template fallback."""

import asyncio
from typing import Optional, Tuple, List, Dict

from app.config import (
    GEMINI_ENABLED,
    GEMINI_API_KEY,
    GEMINI_MODEL,
    GEMINI_TIMEOUT,
    MODEL_NAME
)


def generate_template_report(score: int, model: str, media_type: str = "image") -> str:
    """
    Generate template-based report.
    
    Args:
        score: Integer score 0-100
        model: Model name
        media_type: "image" or "video"
        
    Returns:
        Markdown formatted report
    """
    # Determine range
    if score <= 30:
        range_label = "Low"
        interpretation = "shows low likelihood of AI generation"
    elif score <= 70:
        range_label = "Medium"
        interpretation = "shows moderate indicators of potential AI generation"
    else:
        range_label = "High"
        interpretation = "shows strong indicators consistent with AI generation"
    
    media_specific = "image" if media_type == "image" else "video"
    
    report = f"""## GAIC {media_type.title()} Forensics Report

**Model Used:** {model}  
**Score:** {score}/100 ({range_label} Range)

### Summary

This {media_specific} {interpretation}. The score is derived from analyzing visual patterns, compression artifacts, and statistical features typical of AI-generated content using the **{model}** detector with Grad-CAM explainability.

### Interpretation Guidelines

- **Low (0-30):** Likely authentic or minimally processed
- **Medium (30-70):** Inconclusive; may have AI elements or heavy editing
- **High (70-100):** Strong AI generation indicators detected

### Important Notes

⚠️ **This score is experimental and non-diagnostic.** It should not be used as the sole basis for determining {media_specific} authenticity. Multiple factors can influence the score including:

- {media_specific.title()} compression and resaving
- Post-processing and editing
- {media_specific.title()} source and quality
- Model limitations and biases

### Recommendations

For critical applications, we recommend:
1. Using multiple detection methods
2. Consulting with forensic experts
3. Examining {media_specific} metadata and provenance
4. Considering the context of {media_specific} usage

---

*Report generated by GAIC Detector v2.0 | Taiwan FactCheck Center Demo*
"""
    
    return report


async def generate_gemini_report(
    score: int,
    model: str,
    media_type: str = "image",
    extra_context: Optional[Dict] = None
) -> Optional[str]:
    """
    Generate Gemini-based report with timeout.
    
    Args:
        score: Integer score 0-100
        model: Model name
        media_type: "image" or "video"
        extra_context: Optional dict with additional context (for video: frame info)
        
    Returns:
        Markdown report or None if timeout/error
    """
    if not GEMINI_ENABLED or not GEMINI_API_KEY:
        return None
    
    try:
        import base64
        import aiohttp

        # v1beta endpoint works with gemini-2.5-flash for text+image
        url = f"https://generativelanguage.googleapis.com/v1beta/models/{GEMINI_MODEL}:generateContent?key={GEMINI_API_KEY}"

        # Collect optional context including heatmap
        heatmap_b64 = None
        inference_ms = None
        orig_size = None

        if extra_context:
            heatmap_b64 = extra_context.get("heatmap_png_b64")
            inference_ms = extra_context.get("inference_ms")
            orig_size = extra_context.get("orig_size")

        # Human-friendly strings
        if isinstance(orig_size, (list, tuple)) and len(orig_size) == 2:
            size_str = f"{orig_size[0]}x{orig_size[1]}"
        else:
            size_str = "未提供"
        t_str = f"約 {inference_ms} ms" if inference_ms is not None else "未提供"

        # Build prompt in zh-TW with heatmap context
        if media_type == "video" and extra_context and "frames" in extra_context:
            frames_info = extra_context["frames"]
            frames_desc = "\n".join([
                f"- 影格 {idx+1} @ {f['timestamp']:.1f}s：分數 {f['score']}/100"
                for idx, f in enumerate(frames_info[:3])
            ])
            prompt = (
                "用繁體中文、Markdown 簡短輸出。\n"
                f"影片分數：{score}/100，模型：{model}，解析度：{size_str}，推論時間：{t_str}\n"
                f"可疑影格摘要：\n{frames_desc}\n"
                "請輸出：\n"
                "- 觀察(2句)：描述可疑區域位置與疑點。\n"
                "- 限制(1句)：不確定性。\n"
                "- 建議(1句)：後續查核。\n"
            )
        else:
            likelihood = (
                "低度 AI 生成可能" if score <= 30 else
                "中度 AI 生成可能" if score <= 70 else
                "高度 AI 生成可能"
            )
            # Enhanced prompt when heatmap is available
            if heatmap_b64:
                prompt = (
                    "你是一位專門分析 AI 生成圖像的鑑識專家。\n\n"
                    "這張圖片已經疊合了一層「可疑度熱力圖」：\n"
                    "- 顏色越接近紅色或黃色，代表 AI 偵測模型覺得越可疑\n"
                    "- 顏色接近藍色、綠色或透明，代表比較不可疑\n\n"
                    f"影像分數：{score}/100（{likelihood}）\n"
                    f"模型：{model}，解析度：{size_str}，推論時間：{t_str}\n\n"
                    "請根據這張「原圖＋熱力圖」用繁體中文完成以下任務：\n\n"
                    "1. 整體判斷（1-2句）\n"
                    "   - 根據熱力圖分佈判斷這張圖是否可能是 AI 生成\n\n"
                    "2. 可疑區域說明（找出 2-3 個最可疑區域）\n"
                    "   - 依照相對位置描述（例如：左上角、右下角、畫面中央、人物臉部等）\n"
                    "   - 說明該區域為什麼可疑（熱力圖顏色 + 視覺上的不自然之處）\n\n"
                    "3. 總結與限制（1-2句）\n"
                    "   - 強調這只是輔助判讀，不是 100% 確定的證據\n\n"
                    "請用 Markdown 格式輸出，簡潔清楚即可。"
                )
            else:
                # Fallback to text-only prompt
                prompt = (
                    "用繁體中文、Markdown 簡短輸出。\n"
                    f"影像分數：{score}/100（{likelihood}），模型：{model}，解析度：{size_str}，推論時間：{t_str}\n"
                    "請輸出：\n"
                    "- 觀察(2句)：描述可疑區域位置與疑點。\n"
                    "- 限制(1句)：不確定性或品質限制。\n"
                    "- 建議(1句)：後續查核。\n"
                )

        # Build parts: include heatmap image if available
        parts = []
        if heatmap_b64:
            # Add heatmap image as first part
            parts.append({
                "inlineData": {
                    "mimeType": "image/png",
                    "data": heatmap_b64
                }
            })
        # Add text prompt
        parts.append({"text": prompt})

        async def generate():
            # Minimal payload (no generationConfig) to avoid MAX_TOKENS oddities
            payload = {
                "contents": [{"parts": parts}]
            }

            async with aiohttp.ClientSession() as session:
                async with session.post(url, json=payload, timeout=aiohttp.ClientTimeout(total=GEMINI_TIMEOUT)) as resp:
                    if resp.status != 200:
                        error_text = await resp.text()
                        raise Exception(f"Gemini API error {resp.status}: {error_text}")
                    
                    data = await resp.json()
                    candidates = data.get("candidates", [])
                    if not candidates:
                        raise Exception(f"No candidates in Gemini response: {data}")
                    content = candidates[0].get("content")
                    parts_resp = []
                    if isinstance(content, dict):
                        parts_resp = content.get("parts") or []
                    elif isinstance(content, list):
                        parts_resp = content
                    text_chunks = []
                    for p in parts_resp:
                        if isinstance(p, dict) and "text" in p:
                            text_chunks.append(p.get("text", ""))
                        elif isinstance(p, str):
                            text_chunks.append(p)
                    result_text = "".join(text_chunks).strip()
                    if not result_text:
                        raise Exception(f"Gemini response has no text parts: {data}")
                    return result_text

        result = await asyncio.wait_for(generate(), timeout=GEMINI_TIMEOUT)
        return result
        
    except asyncio.TimeoutError:
        print("Gemini generation timeout")
        return None
    except Exception as e:
        print(f"Gemini generation error: {e}")
        import traceback
        traceback.print_exc()
        return None


async def generate_report(
    score: int,
    model: str,
    media_type: str = "image",
    extra_context: Optional[Dict] = None
) -> Tuple[str, Optional[str]]:
    """
    Generate report with Gemini attempt and template fallback.
    
    Args:
        score: Integer score 0-100
        model: Model name
        media_type: "image" or "video"
        extra_context: Optional dict with additional context
        
    Returns:
        Tuple of (report_markdown, error_code or None)
    """
    error = None
    
    # Try Gemini first
    gemini_report = await generate_gemini_report(score, model, media_type, extra_context)
    
    if gemini_report:
        return gemini_report, None
    
    # Fallback to template
    if GEMINI_ENABLED:
        error = "REPORT_GEN_ERROR"
    
    template_report = generate_template_report(score, model, media_type)
    return template_report, error
