"""Report generation with LLM and template fallback."""

import asyncio
from typing import Optional, Tuple

from app.config import LLM_ENABLED, LLM_API_KEY, LLM_MODEL, TIMEOUT_LLM


def generate_template_report(score: int, model: str) -> str:
    """
    Generate template-based report.
    
    Args:
        score: Integer score 0-100
        model: Model name
        
    Returns:
        Markdown formatted report
    """
    # Determine range
    if score <= 30:
        range_label = "Low"
        interpretation = "shows low likelihood of AI generation"
    elif score <= 70:
        range_label = "Medium"
        interpretation = "shows moderate indicators of potential AI generation"
    else:
        range_label = "High"
        interpretation = "shows strong indicators consistent with AI generation"
    
    report = f"""## GAIC Image Forensics Report

**Model Used:** {model}  
**Score:** {score}/100 ({range_label} Range)

### Summary

This image {interpretation}. The score is derived from analyzing visual patterns, compression artifacts, and statistical features typical of AI-generated images.

### Interpretation Guidelines

- **Low (0-30):** Likely authentic or minimally processed
- **Medium (30-70):** Inconclusive; may have AI elements or heavy editing
- **High (70-100):** Strong AI generation indicators detected

### Important Notes

⚠️ **This score is experimental and non-diagnostic.** It should not be used as the sole basis for determining image authenticity. Multiple factors can influence the score including:

- Image compression and resaving
- Post-processing and editing
- Image source and quality
- Model limitations and biases

### Recommendations

For critical applications, we recommend:
1. Using multiple detection methods
2. Consulting with forensic experts
3. Examining image metadata and provenance
4. Considering the context of image usage

---

*Report generated by GAIC Detector v1.0 | Taiwan FactCheck Center Demo*
"""
    
    return report


async def generate_llm_report(score: int, model: str, image_features: Optional[dict] = None) -> Optional[str]:
    """
    Generate LLM-based report with timeout.
    
    Args:
        score: Integer score 0-100
        model: Model name
        image_features: Optional dictionary of image features
        
    Returns:
        Markdown report or None if timeout/error
    """
    if not LLM_ENABLED or not LLM_API_KEY:
        return None
    
    try:
        # Import here to avoid dependency issues
        import openai
        
        client = openai.AsyncOpenAI(api_key=LLM_API_KEY)
        
        prompt = f"""Generate a concise forensic report for an AI-generated image detection result.

Score: {score}/100
Model: {model}

Provide a brief explanation in English covering:
1. What the score indicates (2 sentences max)
2. Key detection factors (2-3 bullet points)
3. Important disclaimer about experimental nature

Use professional but accessible language. Keep total length under 200 words.
Format in Markdown."""

        # Run with timeout
        response = await asyncio.wait_for(
            client.chat.completions.create(
                model=LLM_MODEL,
                messages=[{"role": "user", "content": prompt}],
                max_tokens=300,
                temperature=0.7
            ),
            timeout=TIMEOUT_LLM
        )
        
        return response.choices[0].message.content
        
    except asyncio.TimeoutError:
        print("LLM generation timeout")
        return None
    except Exception as e:
        print(f"LLM generation error: {e}")
        return None


async def generate_report(score: int, model: str) -> Tuple[str, Optional[str]]:
    """
    Generate report with LLM attempt and template fallback.
    
    Args:
        score: Integer score 0-100
        model: Model name
        
    Returns:
        Tuple of (report_markdown, error_code or None)
    """
    error = None
    
    # Try LLM first
    llm_report = await generate_llm_report(score, model)
    
    if llm_report:
        return llm_report, None
    
    # Fallback to template
    if LLM_ENABLED:
        error = "REPORT_GEN_TIMEOUT" if LLM_API_KEY else "REPORT_GEN_ERROR"
    
    template_report = generate_template_report(score, model)
    return template_report, error
