"""Report generation with Gemini LLM and template fallback."""

import asyncio
from typing import Optional, Tuple, List, Dict

from app.config import (
    GEMINI_ENABLED,
    GEMINI_API_KEY,
    GEMINI_MODEL,
    GEMINI_TIMEOUT,
    MODEL_NAME
)


def generate_template_report(score: int, model: str, media_type: str = "image") -> str:
    """
    Generate template-based report.
    
    Args:
        score: Integer score 0-100
        model: Model name
        media_type: "image" or "video"
        
    Returns:
        Markdown formatted report
    """
    # Determine range
    if score <= 30:
        range_label = "Low"
        interpretation = "shows low likelihood of AI generation"
    elif score <= 70:
        range_label = "Medium"
        interpretation = "shows moderate indicators of potential AI generation"
    else:
        range_label = "High"
        interpretation = "shows strong indicators consistent with AI generation"
    
    media_specific = "image" if media_type == "image" else "video"
    
    report = f"""## GAIC {media_type.title()} Forensics Report

**Model Used:** {model}  
**Score:** {score}/100 ({range_label} Range)

### Summary

This {media_specific} {interpretation}. The score is derived from analyzing visual patterns, compression artifacts, and statistical features typical of AI-generated content using the **{model}** detector with Grad-CAM explainability.

### Interpretation Guidelines

- **Low (0-30):** Likely authentic or minimally processed
- **Medium (30-70):** Inconclusive; may have AI elements or heavy editing
- **High (70-100):** Strong AI generation indicators detected

### Important Notes

⚠️ **This score is experimental and non-diagnostic.** It should not be used as the sole basis for determining {media_specific} authenticity. Multiple factors can influence the score including:

- {media_specific.title()} compression and resaving
- Post-processing and editing
- {media_specific.title()} source and quality
- Model limitations and biases

### Recommendations

For critical applications, we recommend:
1. Using multiple detection methods
2. Consulting with forensic experts
3. Examining {media_specific} metadata and provenance
4. Considering the context of {media_specific} usage

---

*Report generated by GAIC Detector v2.0 | Taiwan FactCheck Center Demo*
"""
    
    return report


async def generate_gemini_report(
    score: int,
    model: str,
    media_type: str = "image",
    extra_context: Optional[Dict] = None
) -> Optional[str]:
    """
    Generate Gemini-based report with timeout.
    
    Args:
        score: Integer score 0-100
        model: Model name
        media_type: "image" or "video"
        extra_context: Optional dict with additional context (for video: frame info)
        
    Returns:
        Markdown report or None if timeout/error
    """
    if not GEMINI_ENABLED or not GEMINI_API_KEY:
        return None
    
    try:
        # Import here to avoid dependency issues
        import google.generativeai as genai
        
        # Configure Gemini
        genai.configure(api_key=GEMINI_API_KEY)
        gemini_model = genai.GenerativeModel(GEMINI_MODEL)
        
        # Build prompt based on media type
        if media_type == "video" and extra_context and "frames" in extra_context:
            # Video analysis prompt
            frames_info = extra_context["frames"]
            frames_desc = "\n".join([
                f"- Frame at {f['timestamp']:.1f}s: score {f['score']}/100"
                for f in frames_info[:3]  # Top 3 frames
            ])
            
            prompt = f"""You are an AI forensics assistant helping fact-checkers.

An AI-generated content detector ({model}) analyzed {extra_context.get('num_frames', 16)} frames from this video.

Most suspicious frames:
{frames_desc}

Video-level score: {score}/100 (highest frame score)

Write a concise video-level explanation (3-4 sentences) in English that:
1. Summarizes the AI-generation likelihood
2. Mentions temporal patterns if any
3. States limitations and uncertainty
4. Avoids definitive claims

Format: Markdown"""
        else:
            # Image analysis prompt
            prompt = f"""You are an AI forensics assistant helping fact-checkers.

An AI-generated image detector ({model}) analyzed this image and produced a score of {score}/100.

Score interpretation:
- 0-30: Low likelihood
- 30-70: Medium likelihood  
- 70-100: High likelihood

Write a concise explanation (3-4 sentences) in English that:
1. Explains what the score indicates
2. Mentions key suspicious patterns (if score is high)
3. States limitations and uncertainty
4. Avoids claiming the image is definitively fake or real

Format: Markdown"""
        
        # Generate with timeout
        async def generate():
            response = await gemini_model.generate_content_async(prompt)
            return response.text
        
        result = await asyncio.wait_for(generate(), timeout=GEMINI_TIMEOUT)
        return result
        
    except asyncio.TimeoutError:
        print("Gemini generation timeout")
        return None
    except Exception as e:
        print(f"Gemini generation error: {e}")
        import traceback
        traceback.print_exc()
        return None


async def generate_report(
    score: int,
    model: str,
    media_type: str = "image",
    extra_context: Optional[Dict] = None
) -> Tuple[str, Optional[str]]:
    """
    Generate report with Gemini attempt and template fallback.
    
    Args:
        score: Integer score 0-100
        model: Model name
        media_type: "image" or "video"
        extra_context: Optional dict with additional context
        
    Returns:
        Tuple of (report_markdown, error_code or None)
    """
    error = None
    
    # Try Gemini first
    gemini_report = await generate_gemini_report(score, model, media_type, extra_context)
    
    if gemini_report:
        return gemini_report, None
    
    # Fallback to template
    if GEMINI_ENABLED:
        error = "REPORT_GEN_TIMEOUT" if GEMINI_API_KEY else "REPORT_GEN_ERROR"
    
    template_report = generate_template_report(score, model, media_type)
    return template_report, error
